name: Primer WorkFlow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21.0.2' 
          distribution: 'temurin'

      - name: Compile project
        run: |
          cd Back-Barrera
          mvn compile  

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21.0.2'
          distribution: 'temurin'

      - name: Run tests
        run: |
          cd Back-Barrera
          mvn verify

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21.0.2'

      - name: Build jar
        run: mvn package -DskipTests
      
      - name: Azure Web App Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'CVDS-TaskManager'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./target/TaskManager-0.0.1-SNAPSHOT.jar
